settings:
  title: 'WebX+ Status'
  url: 'https://status.webxplus.org' # used for Slack messages
  logo: favicon.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: website # unique identifier
    name: 'Website & Registrar'
    description: '' # default=empty
    url: 'https://www.wbxplus.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: dns-primary
    name: Primary DNS
    description: 'Primary DNS server for WebX & WebX+ requests'
    url: 'https://dns-one.webxplus.org/uptime'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: dns-secodary
    name: Secondary DNS
    description: 'Secondary DNS server for WebX & WebX+ requests'
    url: 'https://dns-two.webxplus.org/uptime'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
