name: Deploy

on:
  push:
    branches:
      - main
  repository_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn install
    - run: yarn build
      env:
        NODE_ENV: production
    - name: Publish
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        preCommands: |
          wrangler kv:namespace create KV_STATUS_PAGE || true
          export KV_NAMESPACE_ID=$(npx @cloudflare/wrangler@1 kv:namespace list 2> >(tee stderr.log >&2) | head -1 | node -pe "JSON.parse(fs.readFileSync('/dev/stdin').toString()).find(kv => kv.title.includes('KV_STATUS_PAGE')).id")
          echo "[env.production]" >> wrangler.toml
          echo "kv_namespaces = [{binding=\"KV_STATUS_PAGE\", id=\"${KV_NAMESPACE_ID}\"}]" >> wrangler.toml
        postCommands: |
          yarn kv-gc
        secrets: |
          SECRET_CF_ZONE_ID
          SECRET_CF_API_TOKEN
          SECRET_DISCORD_WEBHOOK_URL
          SECRET_DNS_ROUTE_PRIMARY
          SECRET_DNS_ROUTE_SECONDARY
        environment: production
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        SECRET_CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        SECRET_CF_API_TOKEN: ${{secrets.CF_API_TOKEN}}
        SECRET_DISCORD_WEBHOOK_URL: ${{secrets.SECRET_DISCORD_WEBHOOK_URL}}
        SECRET_DNS_ROUTE_PRIMARY: ${{secrets.PRIMARY_HOST}}
        SECRET_DNS_ROUTE_SECONDARY: ${{secrets.SECONDARY_HOST}}
